using AuxiliumLab.AiSandbox.Infrastructure.Configuration.Preconditions;

namespace AuxiliumLab.AiSandbox.ApplicationServices.Commands.Playground.CreatePlayground;

public readonly record struct CreatePlaygroundCommandParameters(MapConfiguration MapConfiguration, HeroConfiguration HeroConfiguration, EnemyConfiguration EnemyConfiguration);

